// LinkedIn's industry codes (Industry Codes V2,
// learn.microsoft.com/linkedin/shared/references/reference-tables/industry-codes-v2)
// for each name in INDUSTRIES, which is how prospect search filters by
// industry. A few names cover several of LinkedIn's codes.
const INDUSTRY_CODES: Record<string, number | number[]> = {
  "Accounting": 47,
  "Advertising Services": 80,
  "Airlines and Aviation": 94,
  "Alternative Dispute Resolution": 120,
  "Alternative Medicine": 125,
  "Animation and Post-production": 127,
  "Appliances, Electrical, and Electronics Manufacturing": 112,
  "Architecture and Planning": 50,
  "Armed Forces": 71,
  "Artists and Writers": 38,
  "Automation Machinery Manufacturing": 147,
  "Aviation and Aerospace Component Manufacturing": 52,
  "Banking": 41,
  "Beverage Manufacturing": 142,
  "Biotechnology Research": 12,
  "Book and Periodical Publishing": 82,
  "Broadcast Media Production and Distribution": 36,
  "Building Materials": 3197,
  "Business Consulting and Services": 11,
  "Business Supplies and Equipment": 3211,
  "Capital Markets": 129,
  "Chemical Manufacturing": 54,
  "Civic and Social Organizations": 90,
  "Civil Engineering": 51,
  "Commercial Real Estate": 3219,
  "Computer and Network Security": 118,
  "Computer Games": 109,
  "Computer Hardware Manufacturing": 3,
  "Computer Networking Products": 5,
  "Construction": 48,
  "Consumer Goods": 3192,
  "Consumer Services": 91,
  "Cosmetics": 3189,
  "Dairy Product Manufacturing": 65,
  "Defense and Space Manufacturing": 1,
  "Design Services": 99,
  "E-Learning Providers": 132,
  "Education Administration Programs": 69,
  "Environmental Services": 86,
  "Events Services": 110,
  "Executive Offices": 76,
  "Facilities Services": 122,
  "Farming": 63,
  "Financial Services": 43,
  "Fine Art": 3196,
  "Fisheries": 66,
  "Food and Beverage Manufacturing": 23,
  "Food and Beverage Services": 34,
  "Food Production": 3224,
  "Fundraising": 101,
  "Furniture and Home Furnishings Manufacturing": 26,
  "Gambling Facilities and Casinos": 29,
  "Glass, Ceramics and Concrete Manufacturing": 145,
  "Government Administration": 75,
  "Government Relations Services": 148,
  "Graphic Design": 140,
  "Higher Education": 68,
  "Hospitality": 31,
  "Hospitals and Health Care": 14,
  "Human Resources Services": 137,
  "Import and Export": 3209,
  "Individual and Family Services": 88,
  "Industrial Machinery Manufacturing": 135,
  "Information Services": 84,
  "Insurance": 42,
  "International Affairs": 74,
  "International Trade and Development": 141,
  "Internet Publishing": 3132,
  "Investment Banking": 45,
  "Investment Management": 46,
  "IT Services and IT Consulting": 96,
  "Law Enforcement": 77,
  "Law Practice": 9,
  "Legal Services": 10,
  "Legislative Offices": 72,
  "Leisure, Travel and Tourism": [3194, 30],
  "Libraries": 85,
  "Logistics and Supply Chain": 116,
  "Luxury Goods and Jewelry": 3212,
  "Machinery Manufacturing": 55,
  "Maritime Transportation": 95,
  "Market Research": 97,
  "Marketing Services": 1862,
  "Measuring and Control Instrument Manufacturing": 983,
  "Media Production": 126,
  "Medical Equipment Manufacturing": 17,
  "Medical Practices": 13,
  "Mental Health Care": 139,
  "Military and International Affairs": 2391,
  "Mining": 56,
  "Mobile Gaming Apps": 3131,
  "Motor Vehicle Manufacturing": 53,
  "Movies, Videos and Sound": 35,
  "Museums, Historical Sites, and Zoos": 37,
  "Musicians": 115,
  "Nanotechnology Research": 114,
  "Newspaper Publishing": 81,
  "Non-profit Organizations": 100,
  "Oil and Gas": 57,
  "Online Audio and Video Media": 113,
  "Outsourcing and Offshoring Consulting": 123,
  "Packaging and Containers Manufacturing": 146,
  "Paper and Forest Product Manufacturing": 61,
  "Performing Arts": 39,
  "Personal Care Product Manufacturing": 18,
  "Pharmaceutical Manufacturing": 15,
  "Philanthropic Fundraising Services": 131,
  "Photography": 136,
  "Plastics Manufacturing": 117,
  "Political Organizations": 107,
  "Primary and Secondary Education": 67,
  "Printing Services": 83,
  "Professional Training and Coaching": 105,
  "Public Policy Offices": 79,
  "Public Relations and Communications Services": 98,
  "Public Safety": 78,
  "Publishing": [82, 81, 1600, 1602, 3132],
  "Railroad Equipment Manufacturing": 62,
  "Ranching": 64,
  "Real Estate": 44,
  "Recreational Facilities": 40,
  "Religious Institutions": 89,
  "Renewable Energy Semiconductor Manufacturing": 144,
  "Research Services": 70,
  "Restaurants": 32,
  "Retail": 27,
  "Retail Apparel and Fashion": 19,
  "Retail Groceries": 22,
  "Retail Office Equipment": 138,
  "Security and Investigations": 121,
  "Semiconductor Manufacturing": 7,
  "Shipbuilding": 58,
  "Software Development": 4,
  "Spectator Sports": 33,
  "Sporting Goods Manufacturing": 20,
  "Sports and Recreation Instruction": 2027,
  "Staffing and Recruiting": 104,
  "Strategic Management Services": 102,
  "Technology, Information and Internet": 6,
  "Telecommunications": 8,
  "Textile Manufacturing": 60,
  "Think Tanks": 130,
  "Tobacco Manufacturing": 21,
  "Translation and Localization": 108,
  "Transportation, Logistics, Supply Chain and Storage": 116,
  "Truck Transportation": 92,
  "Utilities": 59,
  "Venture Capital and Private Equity Principals": 106,
  "Veterinary Services": 16,
  "Warehousing and Storage": 93,
  "Wellness and Fitness Services": 124,
  "Wholesale": 133,
  "Wholesale Building Materials": 49,
  "Wine and Spirits": 3220,
  "Wireless Services": 119,
  "Writing and Editing": 103,
  "Zoos and Botanical Gardens": 2163,
}

/** The codes for some industry names; unknown names are skipped. At most 20, as the search accepts. */
export function industryCodes(names: readonly string[] | undefined): string[] {
  const codes = (names ?? []).flatMap((n) => [INDUSTRY_CODES[n] ?? []].flat())
  return [...new Set(codes)].slice(0, 20).map(String)
}
