// LinkedIn's industry taxonomy, which is what Generect's `company_industries`
// filter matches against. Values outside this list do NOT error — the API
// returns 200 with zero results — so keep these strings exact.
export const INDUSTRIES = [
  "Accounting",
  "Advertising Services",
  "Airlines and Aviation",
  "Alternative Dispute Resolution",
  "Alternative Medicine",
  "Animation and Post-production",
  "Appliances, Electrical, and Electronics Manufacturing",
  "Architecture and Planning",
  "Armed Forces",
  "Artists and Writers",
  "Automation Machinery Manufacturing",
  "Aviation and Aerospace Component Manufacturing",
  "Banking",
  "Beverage Manufacturing",
  "Biotechnology Research",
  "Book and Periodical Publishing",
  "Broadcast Media Production and Distribution",
  "Building Materials",
  "Business Consulting and Services",
  "Business Supplies and Equipment",
  "Capital Markets",
  "Chemical Manufacturing",
  "Civic and Social Organizations",
  "Civil Engineering",
  "Commercial Real Estate",
  "Computer and Network Security",
  "Computer Games",
  "Computer Hardware Manufacturing",
  "Computer Networking Products",
  "Construction",
  "Consumer Goods",
  "Consumer Services",
  "Cosmetics",
  "Dairy Product Manufacturing",
  "Defense and Space Manufacturing",
  "Design Services",
  "E-Learning Providers",
  "Education Administration Programs",
  "Environmental Services",
  "Events Services",
  "Executive Offices",
  "Facilities Services",
  "Farming",
  "Financial Services",
  "Fine Art",
  "Fisheries",
  "Food and Beverage Manufacturing",
  "Food and Beverage Services",
  "Food Production",
  "Fundraising",
  "Furniture and Home Furnishings Manufacturing",
  "Gambling Facilities and Casinos",
  "Glass, Ceramics and Concrete Manufacturing",
  "Government Administration",
  "Government Relations Services",
  "Graphic Design",
  "Higher Education",
  "Hospitality",
  "Hospitals and Health Care",
  "Human Resources Services",
  "Import and Export",
  "Individual and Family Services",
  "Industrial Machinery Manufacturing",
  "Information Services",
  "Insurance",
  "International Affairs",
  "International Trade and Development",
  "Internet Publishing",
  "Investment Banking",
  "Investment Management",
  "IT Services and IT Consulting",
  "Law Enforcement",
  "Law Practice",
  "Legal Services",
  "Legislative Offices",
  "Leisure, Travel and Tourism",
  "Libraries",
  "Logistics and Supply Chain",
  "Luxury Goods and Jewelry",
  "Machinery Manufacturing",
  "Maritime Transportation",
  "Market Research",
  "Marketing Services",
  "Measuring and Control Instrument Manufacturing",
  "Media Production",
  "Medical Equipment Manufacturing",
  "Medical Practices",
  "Mental Health Care",
  "Military and International Affairs",
  "Mining",
  "Mobile Gaming Apps",
  "Motor Vehicle Manufacturing",
  "Movies, Videos and Sound",
  "Museums, Historical Sites, and Zoos",
  "Musicians",
  "Nanotechnology Research",
  "Newspaper Publishing",
  "Non-profit Organizations",
  "Oil and Gas",
  "Online Audio and Video Media",
  "Outsourcing and Offshoring Consulting",
  "Packaging and Containers Manufacturing",
  "Paper and Forest Product Manufacturing",
  "Performing Arts",
  "Personal Care Product Manufacturing",
  "Pharmaceutical Manufacturing",
  "Philanthropic Fundraising Services",
  "Photography",
  "Plastics Manufacturing",
  "Political Organizations",
  "Primary and Secondary Education",
  "Printing Services",
  "Professional Training and Coaching",
  "Public Policy Offices",
  "Public Relations and Communications Services",
  "Public Safety",
  "Publishing",
  "Railroad Equipment Manufacturing",
  "Ranching",
  "Real Estate",
  "Recreational Facilities",
  "Religious Institutions",
  "Renewable Energy Semiconductor Manufacturing",
  "Research Services",
  "Restaurants",
  "Retail",
  "Retail Apparel and Fashion",
  "Retail Groceries",
  "Retail Office Equipment",
  "Security and Investigations",
  "Semiconductor Manufacturing",
  "Shipbuilding",
  "Software Development",
  "Spectator Sports",
  "Sporting Goods Manufacturing",
  "Sports and Recreation Instruction",
  "Staffing and Recruiting",
  "Strategic Management Services",
  "Technology, Information and Internet",
  "Telecommunications",
  "Textile Manufacturing",
  "Think Tanks",
  "Tobacco Manufacturing",
  "Translation and Localization",
  "Transportation, Logistics, Supply Chain and Storage",
  "Truck Transportation",
  "Utilities",
  "Venture Capital and Private Equity Principals",
  "Veterinary Services",
  "Warehousing and Storage",
  "Wellness and Fitness Services",
  "Wholesale",
  "Wholesale Building Materials",
  "Wine and Spirits",
  "Wireless Services",
  "Writing and Editing",
  "Zoos and Botanical Gardens",
]
