// Autocomplete suggestions for the Job Title filter.
//
// A shortcut to common titles, not a closed list: any title can be typed.
// Short forms ("CEO") come first, as the more usual way to write them.
export const JOB_TITLES = [
  // C-suite
  "CEO",
  "CTO",
  "CFO",
  "COO",
  "CMO",
  "CRO",
  "CIO",
  "CPO",
  "CISO",
  "CDO",
  "CSO",
  "CLO",
  "CHRO",
  "Chief Executive Officer",
  "Chief Technology Officer",
  "Chief Financial Officer",
  "Chief Operating Officer",
  "Chief Marketing Officer",
  "Chief Revenue Officer",
  "Chief Information Officer",
  "Chief Product Officer",
  "Chief People Officer",
  "Chief Data Officer",
  "Chief Security Officer",
  "Chief Legal Officer",
  "Chief Human Resources Officer",
  "Chief Strategy Officer",
  "Chief Innovation Officer",
  "Chief Customer Officer",
  "Chief Growth Officer",
  "Chief Design Officer",
  "Chief Analytics Officer",
  "Chief AI Officer",
  "Chief of Staff",

  // Founders / owners / executive
  "Founder",
  "Co-Founder",
  "Founder and CEO",
  "Owner",
  "Co-Owner",
  "Managing Director",
  "Managing Partner",
  "President",
  "Vice President",
  "Executive Vice President",
  "Senior Vice President",
  "Partner",
  "Principal",
  "Board Member",
  "Board Director",
  "Chairman",
  "Chairwoman",
  "General Manager",
  "Regional Manager",
  "Country Manager",

  // VP — by function
  "VP of Sales",
  "VP of Marketing",
  "VP of Engineering",
  "VP of Product",
  "VP of Finance",
  "VP of Operations",
  "VP of People",
  "VP of Human Resources",
  "VP of Customer Success",
  "VP of Customer Experience",
  "VP of Business Development",
  "VP of Data",
  "VP of Data Science",
  "VP of Analytics",
  "VP of Design",
  "VP of Growth",
  "VP of Strategy",
  "VP of IT",
  "VP of Procurement",
  "VP of Legal",
  "VP of Communications",
  "VP of Partnerships",
  "VP of Revenue Operations",
  "VP of Supply Chain",
  "VP of Research",
  "VP of Engineering, Platform",

  // Head of — by function
  "Head of Sales",
  "Head of Marketing",
  "Head of Growth",
  "Head of Engineering",
  "Head of Product",
  "Head of Operations",
  "Head of People",
  "Head of Talent",
  "Head of Finance",
  "Head of Data",
  "Head of Data Science",
  "Head of Analytics",
  "Head of Customer Insights",
  "Head of Consumer Insights",
  "Head of Market Research",
  "Head of Business Intelligence",
  "Head of Design",
  "Head of Partnerships",
  "Head of Customer Success",
  "Head of Customer Support",
  "Head of Strategy",
  "Head of Legal",
  "Head of Procurement",
  "Head of IT",
  "Head of Security",
  "Head of Communications",
  "Head of Content",
  "Head of Brand",
  "Head of Revenue",
  "Head of Revenue Operations",
  "Head of Sales Operations",
  "Head of Supply Chain",
  "Head of Quality",
  "Head of R&D",

  // Director — by function
  "Sales Director",
  "Marketing Director",
  "Engineering Director",
  "Product Director",
  "Operations Director",
  "Finance Director",
  "IT Director",
  "HR Director",
  "Creative Director",
  "Art Director",
  "Design Director",
  "Data Director",
  "Analytics Director",
  "Customer Success Director",
  "Customer Experience Director",
  "Business Development Director",
  "Strategy Director",
  "Legal Director",
  "Communications Director",
  "Brand Director",
  "Technical Director",
  "Quality Director",
  "Supply Chain Director",
  "Procurement Director",
  "Program Director",
  "Regional Sales Director",
  "Director of Revenue Operations",
  "Director of Customer Insights",
  "Director of Market Research",
  "Director of Business Intelligence",

  // Manager — by function
  "Sales Manager",
  "Marketing Manager",
  "Product Manager",
  "Senior Product Manager",
  "Engineering Manager",
  "Operations Manager",
  "Account Manager",
  "Senior Account Manager",
  "Key Account Manager",
  "Project Manager",
  "Program Manager",
  "Office Manager",
  "HR Manager",
  "Talent Manager",
  "Customer Success Manager",
  "Customer Support Manager",
  "Customer Experience Manager",
  "Business Development Manager",
  "Brand Manager",
  "Category Manager",
  "Channel Manager",
  "Partnerships Manager",
  "Content Manager",
  "Community Manager",
  "Social Media Manager",
  "SEO Manager",
  "Growth Manager",
  "Revenue Operations Manager",
  "Sales Operations Manager",
  "Marketing Operations Manager",
  "Data Manager",
  "Analytics Manager",
  "Insights Manager",
  "Market Research Manager",
  "Business Intelligence Manager",
  "IT Manager",
  "Security Manager",
  "Quality Assurance Manager",
  "Supply Chain Manager",
  "Procurement Manager",
  "Logistics Manager",
  "Warehouse Manager",
  "Finance Manager",
  "Accounting Manager",
  "Legal Manager",
  "Recruitment Manager",
  "Training Manager",
  "Compliance Manager",
  "Risk Manager",
  "Vendor Manager",

  // Analyst / insights / research — individual contributor
  "Business Analyst",
  "Senior Business Analyst",
  "Data Analyst",
  "Senior Data Analyst",
  "Data Scientist",
  "Senior Data Scientist",
  "Machine Learning Engineer",
  "Analytics Analyst",
  "Business Intelligence Analyst",
  "BI Analyst",
  "Insights Analyst",
  "Customer Insights Analyst",
  "Consumer Insights Analyst",
  "Product Analyst",
  "Product Insights Analyst",
  "Market Research Analyst",
  "Marketing Analyst",
  "Marketing Research Analyst",
  "Financial Analyst",
  "Senior Financial Analyst",
  "FP&A Analyst",
  "Investment Analyst",
  "Equity Research Analyst",
  "Credit Analyst",
  "Risk Analyst",
  "Operations Analyst",
  "Revenue Operations Analyst",
  "Sales Operations Analyst",
  "Sales Analyst",
  "Pricing Analyst",
  "Supply Chain Analyst",
  "Procurement Analyst",
  "Quality Analyst",
  "Systems Analyst",
  "Security Analyst",
  "Cybersecurity Analyst",
  "Compliance Analyst",
  "HR Analyst",
  "People Analytics Analyst",
  "Reporting Analyst",
  "Research Analyst",
  "Strategy Analyst",
  "UX Researcher",
  "User Researcher",

  // Product / design
  "Product Manager, Growth",
  "Group Product Manager",
  "Product Owner",
  "Product Designer",
  "Senior Product Designer",
  "UX Designer",
  "UI Designer",
  "UX/UI Designer",
  "Visual Designer",
  "Graphic Designer",
  "Interaction Designer",
  "Service Designer",

  // Engineering / IT
  "Software Engineer",
  "Senior Software Engineer",
  "Staff Software Engineer",
  "Principal Engineer",
  "Backend Engineer",
  "Frontend Engineer",
  "Full Stack Engineer",
  "DevOps Engineer",
  "Site Reliability Engineer",
  "Cloud Engineer",
  "Solutions Engineer",
  "Solutions Architect",
  "Systems Engineer",
  "Network Engineer",
  "QA Engineer",
  "Test Engineer",
  "Data Engineer",
  "Analytics Engineer",
  "Platform Engineer",
  "Security Engineer",
  "IT Support Specialist",
  "System Administrator",

  // Sales / business development
  "Account Executive",
  "Senior Account Executive",
  "Enterprise Account Executive",
  "Sales Development Representative",
  "SDR",
  "Business Development Representative",
  "BDR",
  "Business Development Manager",
  "Territory Manager",
  "Regional Sales Manager",
  "Inside Sales Representative",
  "Outside Sales Representative",
  "Sales Engineer",
  "Sales Consultant",
  "Sales Executive",
  "Partnerships Lead",

  // Marketing / content / growth
  "Marketing Specialist",
  "Digital Marketing Manager",
  "Growth Marketer",
  "Performance Marketing Manager",
  "Demand Generation Manager",
  "Product Marketing Manager",
  "Content Strategist",
  "Content Writer",
  "Copywriter",
  "Email Marketing Manager",
  "PR Manager",
  "Communications Specialist",
  "Events Manager",
  "Field Marketing Manager",

  // Customer success / support
  "Customer Success Specialist",
  "Customer Support Specialist",
  "Customer Success Associate",
  "Implementation Specialist",
  "Onboarding Specialist",
  "Technical Support Engineer",

  // Finance / legal / HR / ops
  "Controller",
  "Financial Controller",
  "Accountant",
  "Senior Accountant",
  "Bookkeeper",
  "Treasury Manager",
  "Payroll Manager",
  "General Counsel",
  "Corporate Counsel",
  "Legal Counsel",
  "Paralegal",
  "HR Business Partner",
  "Talent Acquisition Specialist",
  "Recruiter",
  "Senior Recruiter",
  "Technical Recruiter",
  "People Operations Manager",
  "Learning and Development Manager",
  "Consultant",
  "Senior Consultant",
  "Management Consultant",
  "Strategy Consultant",

  // Operations / supply chain / retail
  "Operations Coordinator",
  "Supply Chain Coordinator",
  "Logistics Coordinator",
  "Warehouse Supervisor",
  "Store Manager",
  "Retail Manager",
  "Plant Manager",
  "Production Manager",
  "Manufacturing Engineer",
  "Process Engineer",
  "Continuous Improvement Manager",
]
