// Generect validates locations against LinkedIn's canonical vocabulary and
// returns HTTP 400 ("This location is not listed") for anything outside it.
// Bare region names like "California", "Texas" or "London" are REJECTED —
// sub-country values must be fully qualified as "Region, Country".
//
// Verified against the live API. Loose metro names ("San Francisco Bay Area",
// "Greater Boston", "Greater Seattle Area") are rejected and deliberately
// omitted; "New York City Metropolitan Area" is the one that validates.
export const LOCATIONS = [
  // --- Countries ---
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "Netherlands",
  "Ireland",
  "Spain",
  "Italy",
  "Portugal",
  "Belgium",
  "Switzerland",
  "Austria",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Poland",
  "Czechia",
  "Romania",
  "Greece",
  "Turkey",
  "Israel",
  "United Arab Emirates",
  "Saudi Arabia",
  "India",
  "Singapore",
  "Japan",
  "China",
  "Hong Kong SAR",
  "South Korea",
  "Malaysia",
  "Indonesia",
  "Philippines",
  "Vietnam",
  "Thailand",
  "New Zealand",
  "Brazil",
  "Mexico",
  "Argentina",
  "Chile",
  "Colombia",
  "South Africa",
  "Nigeria",
  "Kenya",
  "Egypt",

  // --- United States, by state ---
  "Alabama, United States",
  "Alaska, United States",
  "Arizona, United States",
  "Arkansas, United States",
  "California, United States",
  "Colorado, United States",
  "Connecticut, United States",
  "Delaware, United States",
  "District of Columbia, United States",
  "Florida, United States",
  "Georgia, United States",
  "Hawaii, United States",
  "Idaho, United States",
  "Illinois, United States",
  "Indiana, United States",
  "Iowa, United States",
  "Kansas, United States",
  "Kentucky, United States",
  "Louisiana, United States",
  "Maine, United States",
  "Maryland, United States",
  "Massachusetts, United States",
  "Michigan, United States",
  "Minnesota, United States",
  "Mississippi, United States",
  "Missouri, United States",
  "Montana, United States",
  "Nebraska, United States",
  "Nevada, United States",
  "New Hampshire, United States",
  "New Jersey, United States",
  "New Mexico, United States",
  "New York, United States",
  "North Carolina, United States",
  "North Dakota, United States",
  "Ohio, United States",
  "Oklahoma, United States",
  "Oregon, United States",
  "Pennsylvania, United States",
  "Rhode Island, United States",
  "South Carolina, United States",
  "South Dakota, United States",
  "Tennessee, United States",
  "Texas, United States",
  "Utah, United States",
  "Vermont, United States",
  "Virginia, United States",
  "Washington, United States",
  "West Virginia, United States",
  "Wisconsin, United States",
  "Wyoming, United States",
  "New York City Metropolitan Area",

  // --- United Kingdom ---
  "England, United Kingdom",
  "Scotland, United Kingdom",
  "Wales, United Kingdom",
  "Northern Ireland, United Kingdom",
  "London Area, United Kingdom",

  // --- Canada ---
  "Ontario, Canada",
  "British Columbia, Canada",
  "Quebec, Canada",
  "Alberta, Canada",
  "Manitoba, Canada",
  "Nova Scotia, Canada",

  // --- Australia ---
  "New South Wales, Australia",
  "Victoria, Australia",
  "Queensland, Australia",
  "Western Australia, Australia",
  "South Australia, Australia",
]
