/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionIndexRouteImport } from './routes/collection/index'
import { Route as SalesTasksRouteImport } from './routes/sales/tasks'
import { Route as SalesPipelineRouteImport } from './routes/sales/pipeline'
import { Route as SSurveyIdRouteImport } from './routes/s/$surveyId'
import { Route as MarketingTemplatesRouteImport } from './routes/marketing/templates'
import { Route as MarketingSurveysRouteImport } from './routes/marketing/surveys'
import { Route as MarketingFormsRouteImport } from './routes/marketing/forms'
import { Route as MarketingContactsRouteImport } from './routes/marketing/contacts'
import { Route as AuthLinkRouteImport } from './routes/auth/link'
import { Route as ApiUsageRouteImport } from './routes/api/usage'
import { Route as ApiUnsubscribeRouteImport } from './routes/api/unsubscribe'
import { Route as ApiSubscribeRouteImport } from './routes/api/subscribe'
import { Route as ApiOptOutRouteImport } from './routes/api/opt-out'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as SalesDealsIndexRouteImport } from './routes/sales/deals/index'
import { Route as MarketingTemplatesIndexRouteImport } from './routes/marketing/templates/index'
import { Route as MarketingSurveysIndexRouteImport } from './routes/marketing/surveys/index'
import { Route as MarketingListsIndexRouteImport } from './routes/marketing/lists/index'
import { Route as MarketingFormsIndexRouteImport } from './routes/marketing/forms/index'
import { Route as MarketingContactsIndexRouteImport } from './routes/marketing/contacts/index'
import { Route as MarketingCompaniesIndexRouteImport } from './routes/marketing/companies/index'
import { Route as MarketingCampaignsIndexRouteImport } from './routes/marketing/campaigns/index'
import { Route as MarketingAnalyticsIndexRouteImport } from './routes/marketing/analytics/index'
import { Route as CollectionProspectSearchIndexRouteImport } from './routes/collection/prospect-search/index'
import { Route as CollectionPersonasIndexRouteImport } from './routes/collection/personas/index'
import { Route as ApiUploadsIndexRouteImport } from './routes/api/uploads/index'
import { Route as SalesDealsIdRouteImport } from './routes/sales/deals/$id'
import { Route as MarketingListsListIdRouteImport } from './routes/marketing/lists/$listId'
import { Route as MarketingFormsFormIdRouteImport } from './routes/marketing/forms/$formId'
import { Route as MarketingContactsImportRouteImport } from './routes/marketing/contacts/import'
import { Route as MarketingCompaniesIdRouteImport } from './routes/marketing/companies/$id'
import { Route as MarketingCampaignsIdRouteImport } from './routes/marketing/campaigns/$id'
import { Route as CollectionPersonasNewRouteImport } from './routes/collection/personas/new'
import { Route as CollectionPersonasPersonaIdRouteImport } from './routes/collection/personas/$personaId'
import { Route as ApiWebhooksBounceRouteImport } from './routes/api/webhooks/bounce'
import { Route as ApiUsageSuppressionsRouteImport } from './routes/api/usage.suppressions'
import { Route as ApiUsageDomainsRouteImport } from './routes/api/usage.domains'
import { Route as ApiUsageAllowanceRouteImport } from './routes/api/usage.allowance'
import { Route as ApiUploadsFilenameRouteImport } from './routes/api/uploads/$filename'
import { Route as ApiTrackOpenRouteImport } from './routes/api/track/open'
import { Route as ApiTrackClickRouteImport } from './routes/api/track/click'
import { Route as ApiSurveySurveyIdRouteImport } from './routes/api/survey/$surveyId'
import { Route as ApiFormSubmitFormIdRouteImport } from './routes/api/form-submit/$formId'
import { Route as ApiCopilotStreamRouteImport } from './routes/api/copilot/stream'
import { Route as ApiCopilotPermissionRouteImport } from './routes/api/copilot/permission'
import { Route as MarketingSurveysSurveyIdIndexRouteImport } from './routes/marketing/surveys/$surveyId/index'
import { Route as MarketingTemplatesTemplateIdEditRouteImport } from './routes/marketing/templates/$templateId/edit'
import { Route as MarketingSurveysSurveyIdEditRouteImport } from './routes/marketing/surveys/$surveyId/edit'
import { Route as ApiWebhooksEmailProviderRouteImport } from './routes/api/webhooks/email.$provider'
import { Route as ApiSurveysSurveyIdTokenRouteImport } from './routes/api/surveys/$surveyId/token'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIndexRoute = CollectionIndexRouteImport.update({
  id: '/collection/',
  path: '/collection/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesTasksRoute = SalesTasksRouteImport.update({
  id: '/sales/tasks',
  path: '/sales/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesPipelineRoute = SalesPipelineRouteImport.update({
  id: '/sales/pipeline',
  path: '/sales/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SSurveyIdRoute = SSurveyIdRouteImport.update({
  id: '/s/$surveyId',
  path: '/s/$surveyId',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingTemplatesRoute = MarketingTemplatesRouteImport.update({
  id: '/marketing/templates',
  path: '/marketing/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingSurveysRoute = MarketingSurveysRouteImport.update({
  id: '/marketing/surveys',
  path: '/marketing/surveys',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingFormsRoute = MarketingFormsRouteImport.update({
  id: '/marketing/forms',
  path: '/marketing/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingContactsRoute = MarketingContactsRouteImport.update({
  id: '/marketing/contacts',
  path: '/marketing/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLinkRoute = AuthLinkRouteImport.update({
  id: '/auth/link',
  path: '/auth/link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsageRoute = ApiUsageRouteImport.update({
  id: '/api/usage',
  path: '/api/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnsubscribeRoute = ApiUnsubscribeRouteImport.update({
  id: '/api/unsubscribe',
  path: '/api/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscribeRoute = ApiSubscribeRouteImport.update({
  id: '/api/subscribe',
  path: '/api/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOptOutRoute = ApiOptOutRouteImport.update({
  id: '/api/opt-out',
  path: '/api/opt-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesDealsIndexRoute = SalesDealsIndexRouteImport.update({
  id: '/sales/deals/',
  path: '/sales/deals/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingTemplatesIndexRoute = MarketingTemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingTemplatesRoute,
} as any)
const MarketingSurveysIndexRoute = MarketingSurveysIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingSurveysRoute,
} as any)
const MarketingListsIndexRoute = MarketingListsIndexRouteImport.update({
  id: '/marketing/lists/',
  path: '/marketing/lists/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingFormsIndexRoute = MarketingFormsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingFormsRoute,
} as any)
const MarketingContactsIndexRoute = MarketingContactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingContactsRoute,
} as any)
const MarketingCompaniesIndexRoute = MarketingCompaniesIndexRouteImport.update({
  id: '/marketing/companies/',
  path: '/marketing/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingCampaignsIndexRoute = MarketingCampaignsIndexRouteImport.update({
  id: '/marketing/campaigns/',
  path: '/marketing/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingAnalyticsIndexRoute = MarketingAnalyticsIndexRouteImport.update({
  id: '/marketing/analytics/',
  path: '/marketing/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionProspectSearchIndexRoute =
  CollectionProspectSearchIndexRouteImport.update({
    id: '/collection/prospect-search/',
    path: '/collection/prospect-search/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CollectionPersonasIndexRoute = CollectionPersonasIndexRouteImport.update({
  id: '/collection/personas/',
  path: '/collection/personas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsIndexRoute = ApiUploadsIndexRouteImport.update({
  id: '/api/uploads/',
  path: '/api/uploads/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesDealsIdRoute = SalesDealsIdRouteImport.update({
  id: '/sales/deals/$id',
  path: '/sales/deals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingListsListIdRoute = MarketingListsListIdRouteImport.update({
  id: '/marketing/lists/$listId',
  path: '/marketing/lists/$listId',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingFormsFormIdRoute = MarketingFormsFormIdRouteImport.update({
  id: '/$formId',
  path: '/$formId',
  getParentRoute: () => MarketingFormsRoute,
} as any)
const MarketingContactsImportRoute = MarketingContactsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => MarketingContactsRoute,
} as any)
const MarketingCompaniesIdRoute = MarketingCompaniesIdRouteImport.update({
  id: '/marketing/companies/$id',
  path: '/marketing/companies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingCampaignsIdRoute = MarketingCampaignsIdRouteImport.update({
  id: '/marketing/campaigns/$id',
  path: '/marketing/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionPersonasNewRoute = CollectionPersonasNewRouteImport.update({
  id: '/collection/personas/new',
  path: '/collection/personas/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionPersonasPersonaIdRoute =
  CollectionPersonasPersonaIdRouteImport.update({
    id: '/collection/personas/$personaId',
    path: '/collection/personas/$personaId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksBounceRoute = ApiWebhooksBounceRouteImport.update({
  id: '/api/webhooks/bounce',
  path: '/api/webhooks/bounce',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsageSuppressionsRoute = ApiUsageSuppressionsRouteImport.update({
  id: '/suppressions',
  path: '/suppressions',
  getParentRoute: () => ApiUsageRoute,
} as any)
const ApiUsageDomainsRoute = ApiUsageDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => ApiUsageRoute,
} as any)
const ApiUsageAllowanceRoute = ApiUsageAllowanceRouteImport.update({
  id: '/allowance',
  path: '/allowance',
  getParentRoute: () => ApiUsageRoute,
} as any)
const ApiUploadsFilenameRoute = ApiUploadsFilenameRouteImport.update({
  id: '/api/uploads/$filename',
  path: '/api/uploads/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackOpenRoute = ApiTrackOpenRouteImport.update({
  id: '/api/track/open',
  path: '/api/track/open',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackClickRoute = ApiTrackClickRouteImport.update({
  id: '/api/track/click',
  path: '/api/track/click',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSurveySurveyIdRoute = ApiSurveySurveyIdRouteImport.update({
  id: '/api/survey/$surveyId',
  path: '/api/survey/$surveyId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormSubmitFormIdRoute = ApiFormSubmitFormIdRouteImport.update({
  id: '/api/form-submit/$formId',
  path: '/api/form-submit/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotStreamRoute = ApiCopilotStreamRouteImport.update({
  id: '/api/copilot/stream',
  path: '/api/copilot/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotPermissionRoute = ApiCopilotPermissionRouteImport.update({
  id: '/api/copilot/permission',
  path: '/api/copilot/permission',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingSurveysSurveyIdIndexRoute =
  MarketingSurveysSurveyIdIndexRouteImport.update({
    id: '/$surveyId/',
    path: '/$surveyId/',
    getParentRoute: () => MarketingSurveysRoute,
  } as any)
const MarketingTemplatesTemplateIdEditRoute =
  MarketingTemplatesTemplateIdEditRouteImport.update({
    id: '/$templateId/edit',
    path: '/$templateId/edit',
    getParentRoute: () => MarketingTemplatesRoute,
  } as any)
const MarketingSurveysSurveyIdEditRoute =
  MarketingSurveysSurveyIdEditRouteImport.update({
    id: '/$surveyId/edit',
    path: '/$surveyId/edit',
    getParentRoute: () => MarketingSurveysRoute,
  } as any)
const ApiWebhooksEmailProviderRoute =
  ApiWebhooksEmailProviderRouteImport.update({
    id: '/api/webhooks/email/$provider',
    path: '/api/webhooks/email/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSurveysSurveyIdTokenRoute = ApiSurveysSurveyIdTokenRouteImport.update({
  id: '/api/surveys/$surveyId/token',
  path: '/api/surveys/$surveyId/token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/opt-out': typeof ApiOptOutRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/api/unsubscribe': typeof ApiUnsubscribeRoute
  '/api/usage': typeof ApiUsageRouteWithChildren
  '/auth/link': typeof AuthLinkRoute
  '/marketing/contacts': typeof MarketingContactsRouteWithChildren
  '/marketing/forms': typeof MarketingFormsRouteWithChildren
  '/marketing/surveys': typeof MarketingSurveysRouteWithChildren
  '/marketing/templates': typeof MarketingTemplatesRouteWithChildren
  '/s/$surveyId': typeof SSurveyIdRoute
  '/sales/pipeline': typeof SalesPipelineRoute
  '/sales/tasks': typeof SalesTasksRoute
  '/collection/': typeof CollectionIndexRoute
  '/api/copilot/permission': typeof ApiCopilotPermissionRoute
  '/api/copilot/stream': typeof ApiCopilotStreamRoute
  '/api/form-submit/$formId': typeof ApiFormSubmitFormIdRoute
  '/api/survey/$surveyId': typeof ApiSurveySurveyIdRoute
  '/api/track/click': typeof ApiTrackClickRoute
  '/api/track/open': typeof ApiTrackOpenRoute
  '/api/uploads/$filename': typeof ApiUploadsFilenameRoute
  '/api/usage/allowance': typeof ApiUsageAllowanceRoute
  '/api/usage/domains': typeof ApiUsageDomainsRoute
  '/api/usage/suppressions': typeof ApiUsageSuppressionsRoute
  '/api/webhooks/bounce': typeof ApiWebhooksBounceRoute
  '/collection/personas/$personaId': typeof CollectionPersonasPersonaIdRoute
  '/collection/personas/new': typeof CollectionPersonasNewRoute
  '/marketing/campaigns/$id': typeof MarketingCampaignsIdRoute
  '/marketing/companies/$id': typeof MarketingCompaniesIdRoute
  '/marketing/contacts/import': typeof MarketingContactsImportRoute
  '/marketing/forms/$formId': typeof MarketingFormsFormIdRoute
  '/marketing/lists/$listId': typeof MarketingListsListIdRoute
  '/sales/deals/$id': typeof SalesDealsIdRoute
  '/api/uploads/': typeof ApiUploadsIndexRoute
  '/collection/personas/': typeof CollectionPersonasIndexRoute
  '/collection/prospect-search/': typeof CollectionProspectSearchIndexRoute
  '/marketing/analytics/': typeof MarketingAnalyticsIndexRoute
  '/marketing/campaigns/': typeof MarketingCampaignsIndexRoute
  '/marketing/companies/': typeof MarketingCompaniesIndexRoute
  '/marketing/contacts/': typeof MarketingContactsIndexRoute
  '/marketing/forms/': typeof MarketingFormsIndexRoute
  '/marketing/lists/': typeof MarketingListsIndexRoute
  '/marketing/surveys/': typeof MarketingSurveysIndexRoute
  '/marketing/templates/': typeof MarketingTemplatesIndexRoute
  '/sales/deals/': typeof SalesDealsIndexRoute
  '/api/surveys/$surveyId/token': typeof ApiSurveysSurveyIdTokenRoute
  '/api/webhooks/email/$provider': typeof ApiWebhooksEmailProviderRoute
  '/marketing/surveys/$surveyId/edit': typeof MarketingSurveysSurveyIdEditRoute
  '/marketing/templates/$templateId/edit': typeof MarketingTemplatesTemplateIdEditRoute
  '/marketing/surveys/$surveyId/': typeof MarketingSurveysSurveyIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/opt-out': typeof ApiOptOutRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/api/unsubscribe': typeof ApiUnsubscribeRoute
  '/api/usage': typeof ApiUsageRouteWithChildren
  '/auth/link': typeof AuthLinkRoute
  '/s/$surveyId': typeof SSurveyIdRoute
  '/sales/pipeline': typeof SalesPipelineRoute
  '/sales/tasks': typeof SalesTasksRoute
  '/collection': typeof CollectionIndexRoute
  '/api/copilot/permission': typeof ApiCopilotPermissionRoute
  '/api/copilot/stream': typeof ApiCopilotStreamRoute
  '/api/form-submit/$formId': typeof ApiFormSubmitFormIdRoute
  '/api/survey/$surveyId': typeof ApiSurveySurveyIdRoute
  '/api/track/click': typeof ApiTrackClickRoute
  '/api/track/open': typeof ApiTrackOpenRoute
  '/api/uploads/$filename': typeof ApiUploadsFilenameRoute
  '/api/usage/allowance': typeof ApiUsageAllowanceRoute
  '/api/usage/domains': typeof ApiUsageDomainsRoute
  '/api/usage/suppressions': typeof ApiUsageSuppressionsRoute
  '/api/webhooks/bounce': typeof ApiWebhooksBounceRoute
  '/collection/personas/$personaId': typeof CollectionPersonasPersonaIdRoute
  '/collection/personas/new': typeof CollectionPersonasNewRoute
  '/marketing/campaigns/$id': typeof MarketingCampaignsIdRoute
  '/marketing/companies/$id': typeof MarketingCompaniesIdRoute
  '/marketing/contacts/import': typeof MarketingContactsImportRoute
  '/marketing/forms/$formId': typeof MarketingFormsFormIdRoute
  '/marketing/lists/$listId': typeof MarketingListsListIdRoute
  '/sales/deals/$id': typeof SalesDealsIdRoute
  '/api/uploads': typeof ApiUploadsIndexRoute
  '/collection/personas': typeof CollectionPersonasIndexRoute
  '/collection/prospect-search': typeof CollectionProspectSearchIndexRoute
  '/marketing/analytics': typeof MarketingAnalyticsIndexRoute
  '/marketing/campaigns': typeof MarketingCampaignsIndexRoute
  '/marketing/companies': typeof MarketingCompaniesIndexRoute
  '/marketing/contacts': typeof MarketingContactsIndexRoute
  '/marketing/forms': typeof MarketingFormsIndexRoute
  '/marketing/lists': typeof MarketingListsIndexRoute
  '/marketing/surveys': typeof MarketingSurveysIndexRoute
  '/marketing/templates': typeof MarketingTemplatesIndexRoute
  '/sales/deals': typeof SalesDealsIndexRoute
  '/api/surveys/$surveyId/token': typeof ApiSurveysSurveyIdTokenRoute
  '/api/webhooks/email/$provider': typeof ApiWebhooksEmailProviderRoute
  '/marketing/surveys/$surveyId/edit': typeof MarketingSurveysSurveyIdEditRoute
  '/marketing/templates/$templateId/edit': typeof MarketingTemplatesTemplateIdEditRoute
  '/marketing/surveys/$surveyId': typeof MarketingSurveysSurveyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/opt-out': typeof ApiOptOutRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/api/unsubscribe': typeof ApiUnsubscribeRoute
  '/api/usage': typeof ApiUsageRouteWithChildren
  '/auth/link': typeof AuthLinkRoute
  '/marketing/contacts': typeof MarketingContactsRouteWithChildren
  '/marketing/forms': typeof MarketingFormsRouteWithChildren
  '/marketing/surveys': typeof MarketingSurveysRouteWithChildren
  '/marketing/templates': typeof MarketingTemplatesRouteWithChildren
  '/s/$surveyId': typeof SSurveyIdRoute
  '/sales/pipeline': typeof SalesPipelineRoute
  '/sales/tasks': typeof SalesTasksRoute
  '/collection/': typeof CollectionIndexRoute
  '/api/copilot/permission': typeof ApiCopilotPermissionRoute
  '/api/copilot/stream': typeof ApiCopilotStreamRoute
  '/api/form-submit/$formId': typeof ApiFormSubmitFormIdRoute
  '/api/survey/$surveyId': typeof ApiSurveySurveyIdRoute
  '/api/track/click': typeof ApiTrackClickRoute
  '/api/track/open': typeof ApiTrackOpenRoute
  '/api/uploads/$filename': typeof ApiUploadsFilenameRoute
  '/api/usage/allowance': typeof ApiUsageAllowanceRoute
  '/api/usage/domains': typeof ApiUsageDomainsRoute
  '/api/usage/suppressions': typeof ApiUsageSuppressionsRoute
  '/api/webhooks/bounce': typeof ApiWebhooksBounceRoute
  '/collection/personas/$personaId': typeof CollectionPersonasPersonaIdRoute
  '/collection/personas/new': typeof CollectionPersonasNewRoute
  '/marketing/campaigns/$id': typeof MarketingCampaignsIdRoute
  '/marketing/companies/$id': typeof MarketingCompaniesIdRoute
  '/marketing/contacts/import': typeof MarketingContactsImportRoute
  '/marketing/forms/$formId': typeof MarketingFormsFormIdRoute
  '/marketing/lists/$listId': typeof MarketingListsListIdRoute
  '/sales/deals/$id': typeof SalesDealsIdRoute
  '/api/uploads/': typeof ApiUploadsIndexRoute
  '/collection/personas/': typeof CollectionPersonasIndexRoute
  '/collection/prospect-search/': typeof CollectionProspectSearchIndexRoute
  '/marketing/analytics/': typeof MarketingAnalyticsIndexRoute
  '/marketing/campaigns/': typeof MarketingCampaignsIndexRoute
  '/marketing/companies/': typeof MarketingCompaniesIndexRoute
  '/marketing/contacts/': typeof MarketingContactsIndexRoute
  '/marketing/forms/': typeof MarketingFormsIndexRoute
  '/marketing/lists/': typeof MarketingListsIndexRoute
  '/marketing/surveys/': typeof MarketingSurveysIndexRoute
  '/marketing/templates/': typeof MarketingTemplatesIndexRoute
  '/sales/deals/': typeof SalesDealsIndexRoute
  '/api/surveys/$surveyId/token': typeof ApiSurveysSurveyIdTokenRoute
  '/api/webhooks/email/$provider': typeof ApiWebhooksEmailProviderRoute
  '/marketing/surveys/$surveyId/edit': typeof MarketingSurveysSurveyIdEditRoute
  '/marketing/templates/$templateId/edit': typeof MarketingTemplatesTemplateIdEditRoute
  '/marketing/surveys/$surveyId/': typeof MarketingSurveysSurveyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/api/mcp'
    | '/api/opt-out'
    | '/api/subscribe'
    | '/api/unsubscribe'
    | '/api/usage'
    | '/auth/link'
    | '/marketing/contacts'
    | '/marketing/forms'
    | '/marketing/surveys'
    | '/marketing/templates'
    | '/s/$surveyId'
    | '/sales/pipeline'
    | '/sales/tasks'
    | '/collection/'
    | '/api/copilot/permission'
    | '/api/copilot/stream'
    | '/api/form-submit/$formId'
    | '/api/survey/$surveyId'
    | '/api/track/click'
    | '/api/track/open'
    | '/api/uploads/$filename'
    | '/api/usage/allowance'
    | '/api/usage/domains'
    | '/api/usage/suppressions'
    | '/api/webhooks/bounce'
    | '/collection/personas/$personaId'
    | '/collection/personas/new'
    | '/marketing/campaigns/$id'
    | '/marketing/companies/$id'
    | '/marketing/contacts/import'
    | '/marketing/forms/$formId'
    | '/marketing/lists/$listId'
    | '/sales/deals/$id'
    | '/api/uploads/'
    | '/collection/personas/'
    | '/collection/prospect-search/'
    | '/marketing/analytics/'
    | '/marketing/campaigns/'
    | '/marketing/companies/'
    | '/marketing/contacts/'
    | '/marketing/forms/'
    | '/marketing/lists/'
    | '/marketing/surveys/'
    | '/marketing/templates/'
    | '/sales/deals/'
    | '/api/surveys/$surveyId/token'
    | '/api/webhooks/email/$provider'
    | '/marketing/surveys/$surveyId/edit'
    | '/marketing/templates/$templateId/edit'
    | '/marketing/surveys/$surveyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/api/mcp'
    | '/api/opt-out'
    | '/api/subscribe'
    | '/api/unsubscribe'
    | '/api/usage'
    | '/auth/link'
    | '/s/$surveyId'
    | '/sales/pipeline'
    | '/sales/tasks'
    | '/collection'
    | '/api/copilot/permission'
    | '/api/copilot/stream'
    | '/api/form-submit/$formId'
    | '/api/survey/$surveyId'
    | '/api/track/click'
    | '/api/track/open'
    | '/api/uploads/$filename'
    | '/api/usage/allowance'
    | '/api/usage/domains'
    | '/api/usage/suppressions'
    | '/api/webhooks/bounce'
    | '/collection/personas/$personaId'
    | '/collection/personas/new'
    | '/marketing/campaigns/$id'
    | '/marketing/companies/$id'
    | '/marketing/contacts/import'
    | '/marketing/forms/$formId'
    | '/marketing/lists/$listId'
    | '/sales/deals/$id'
    | '/api/uploads'
    | '/collection/personas'
    | '/collection/prospect-search'
    | '/marketing/analytics'
    | '/marketing/campaigns'
    | '/marketing/companies'
    | '/marketing/contacts'
    | '/marketing/forms'
    | '/marketing/lists'
    | '/marketing/surveys'
    | '/marketing/templates'
    | '/sales/deals'
    | '/api/surveys/$surveyId/token'
    | '/api/webhooks/email/$provider'
    | '/marketing/surveys/$surveyId/edit'
    | '/marketing/templates/$templateId/edit'
    | '/marketing/surveys/$surveyId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings'
    | '/api/mcp'
    | '/api/opt-out'
    | '/api/subscribe'
    | '/api/unsubscribe'
    | '/api/usage'
    | '/auth/link'
    | '/marketing/contacts'
    | '/marketing/forms'
    | '/marketing/surveys'
    | '/marketing/templates'
    | '/s/$surveyId'
    | '/sales/pipeline'
    | '/sales/tasks'
    | '/collection/'
    | '/api/copilot/permission'
    | '/api/copilot/stream'
    | '/api/form-submit/$formId'
    | '/api/survey/$surveyId'
    | '/api/track/click'
    | '/api/track/open'
    | '/api/uploads/$filename'
    | '/api/usage/allowance'
    | '/api/usage/domains'
    | '/api/usage/suppressions'
    | '/api/webhooks/bounce'
    | '/collection/personas/$personaId'
    | '/collection/personas/new'
    | '/marketing/campaigns/$id'
    | '/marketing/companies/$id'
    | '/marketing/contacts/import'
    | '/marketing/forms/$formId'
    | '/marketing/lists/$listId'
    | '/sales/deals/$id'
    | '/api/uploads/'
    | '/collection/personas/'
    | '/collection/prospect-search/'
    | '/marketing/analytics/'
    | '/marketing/campaigns/'
    | '/marketing/companies/'
    | '/marketing/contacts/'
    | '/marketing/forms/'
    | '/marketing/lists/'
    | '/marketing/surveys/'
    | '/marketing/templates/'
    | '/sales/deals/'
    | '/api/surveys/$surveyId/token'
    | '/api/webhooks/email/$provider'
    | '/marketing/surveys/$surveyId/edit'
    | '/marketing/templates/$templateId/edit'
    | '/marketing/surveys/$surveyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiOptOutRoute: typeof ApiOptOutRoute
  ApiSubscribeRoute: typeof ApiSubscribeRoute
  ApiUnsubscribeRoute: typeof ApiUnsubscribeRoute
  ApiUsageRoute: typeof ApiUsageRouteWithChildren
  AuthLinkRoute: typeof AuthLinkRoute
  MarketingContactsRoute: typeof MarketingContactsRouteWithChildren
  MarketingFormsRoute: typeof MarketingFormsRouteWithChildren
  MarketingSurveysRoute: typeof MarketingSurveysRouteWithChildren
  MarketingTemplatesRoute: typeof MarketingTemplatesRouteWithChildren
  SSurveyIdRoute: typeof SSurveyIdRoute
  SalesPipelineRoute: typeof SalesPipelineRoute
  SalesTasksRoute: typeof SalesTasksRoute
  CollectionIndexRoute: typeof CollectionIndexRoute
  ApiCopilotPermissionRoute: typeof ApiCopilotPermissionRoute
  ApiCopilotStreamRoute: typeof ApiCopilotStreamRoute
  ApiFormSubmitFormIdRoute: typeof ApiFormSubmitFormIdRoute
  ApiSurveySurveyIdRoute: typeof ApiSurveySurveyIdRoute
  ApiTrackClickRoute: typeof ApiTrackClickRoute
  ApiTrackOpenRoute: typeof ApiTrackOpenRoute
  ApiUploadsFilenameRoute: typeof ApiUploadsFilenameRoute
  ApiWebhooksBounceRoute: typeof ApiWebhooksBounceRoute
  CollectionPersonasPersonaIdRoute: typeof CollectionPersonasPersonaIdRoute
  CollectionPersonasNewRoute: typeof CollectionPersonasNewRoute
  MarketingCampaignsIdRoute: typeof MarketingCampaignsIdRoute
  MarketingCompaniesIdRoute: typeof MarketingCompaniesIdRoute
  MarketingListsListIdRoute: typeof MarketingListsListIdRoute
  SalesDealsIdRoute: typeof SalesDealsIdRoute
  ApiUploadsIndexRoute: typeof ApiUploadsIndexRoute
  CollectionPersonasIndexRoute: typeof CollectionPersonasIndexRoute
  CollectionProspectSearchIndexRoute: typeof CollectionProspectSearchIndexRoute
  MarketingAnalyticsIndexRoute: typeof MarketingAnalyticsIndexRoute
  MarketingCampaignsIndexRoute: typeof MarketingCampaignsIndexRoute
  MarketingCompaniesIndexRoute: typeof MarketingCompaniesIndexRoute
  MarketingListsIndexRoute: typeof MarketingListsIndexRoute
  SalesDealsIndexRoute: typeof SalesDealsIndexRoute
  ApiSurveysSurveyIdTokenRoute: typeof ApiSurveysSurveyIdTokenRoute
  ApiWebhooksEmailProviderRoute: typeof ApiWebhooksEmailProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/': {
      id: '/collection/'
      path: '/collection'
      fullPath: '/collection/'
      preLoaderRoute: typeof CollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/tasks': {
      id: '/sales/tasks'
      path: '/sales/tasks'
      fullPath: '/sales/tasks'
      preLoaderRoute: typeof SalesTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/pipeline': {
      id: '/sales/pipeline'
      path: '/sales/pipeline'
      fullPath: '/sales/pipeline'
      preLoaderRoute: typeof SalesPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$surveyId': {
      id: '/s/$surveyId'
      path: '/s/$surveyId'
      fullPath: '/s/$surveyId'
      preLoaderRoute: typeof SSurveyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/templates': {
      id: '/marketing/templates'
      path: '/marketing/templates'
      fullPath: '/marketing/templates'
      preLoaderRoute: typeof MarketingTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/surveys': {
      id: '/marketing/surveys'
      path: '/marketing/surveys'
      fullPath: '/marketing/surveys'
      preLoaderRoute: typeof MarketingSurveysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/forms': {
      id: '/marketing/forms'
      path: '/marketing/forms'
      fullPath: '/marketing/forms'
      preLoaderRoute: typeof MarketingFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/contacts': {
      id: '/marketing/contacts'
      path: '/marketing/contacts'
      fullPath: '/marketing/contacts'
      preLoaderRoute: typeof MarketingContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/link': {
      id: '/auth/link'
      path: '/auth/link'
      fullPath: '/auth/link'
      preLoaderRoute: typeof AuthLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/usage': {
      id: '/api/usage'
      path: '/api/usage'
      fullPath: '/api/usage'
      preLoaderRoute: typeof ApiUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unsubscribe': {
      id: '/api/unsubscribe'
      path: '/api/unsubscribe'
      fullPath: '/api/unsubscribe'
      preLoaderRoute: typeof ApiUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscribe': {
      id: '/api/subscribe'
      path: '/api/subscribe'
      fullPath: '/api/subscribe'
      preLoaderRoute: typeof ApiSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/opt-out': {
      id: '/api/opt-out'
      path: '/api/opt-out'
      fullPath: '/api/opt-out'
      preLoaderRoute: typeof ApiOptOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/deals/': {
      id: '/sales/deals/'
      path: '/sales/deals'
      fullPath: '/sales/deals/'
      preLoaderRoute: typeof SalesDealsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/templates/': {
      id: '/marketing/templates/'
      path: '/'
      fullPath: '/marketing/templates/'
      preLoaderRoute: typeof MarketingTemplatesIndexRouteImport
      parentRoute: typeof MarketingTemplatesRoute
    }
    '/marketing/surveys/': {
      id: '/marketing/surveys/'
      path: '/'
      fullPath: '/marketing/surveys/'
      preLoaderRoute: typeof MarketingSurveysIndexRouteImport
      parentRoute: typeof MarketingSurveysRoute
    }
    '/marketing/lists/': {
      id: '/marketing/lists/'
      path: '/marketing/lists'
      fullPath: '/marketing/lists/'
      preLoaderRoute: typeof MarketingListsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/forms/': {
      id: '/marketing/forms/'
      path: '/'
      fullPath: '/marketing/forms/'
      preLoaderRoute: typeof MarketingFormsIndexRouteImport
      parentRoute: typeof MarketingFormsRoute
    }
    '/marketing/contacts/': {
      id: '/marketing/contacts/'
      path: '/'
      fullPath: '/marketing/contacts/'
      preLoaderRoute: typeof MarketingContactsIndexRouteImport
      parentRoute: typeof MarketingContactsRoute
    }
    '/marketing/companies/': {
      id: '/marketing/companies/'
      path: '/marketing/companies'
      fullPath: '/marketing/companies/'
      preLoaderRoute: typeof MarketingCompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/campaigns/': {
      id: '/marketing/campaigns/'
      path: '/marketing/campaigns'
      fullPath: '/marketing/campaigns/'
      preLoaderRoute: typeof MarketingCampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/analytics/': {
      id: '/marketing/analytics/'
      path: '/marketing/analytics'
      fullPath: '/marketing/analytics/'
      preLoaderRoute: typeof MarketingAnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/prospect-search/': {
      id: '/collection/prospect-search/'
      path: '/collection/prospect-search'
      fullPath: '/collection/prospect-search/'
      preLoaderRoute: typeof CollectionProspectSearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/personas/': {
      id: '/collection/personas/'
      path: '/collection/personas'
      fullPath: '/collection/personas/'
      preLoaderRoute: typeof CollectionPersonasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/': {
      id: '/api/uploads/'
      path: '/api/uploads'
      fullPath: '/api/uploads/'
      preLoaderRoute: typeof ApiUploadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/deals/$id': {
      id: '/sales/deals/$id'
      path: '/sales/deals/$id'
      fullPath: '/sales/deals/$id'
      preLoaderRoute: typeof SalesDealsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/lists/$listId': {
      id: '/marketing/lists/$listId'
      path: '/marketing/lists/$listId'
      fullPath: '/marketing/lists/$listId'
      preLoaderRoute: typeof MarketingListsListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/forms/$formId': {
      id: '/marketing/forms/$formId'
      path: '/$formId'
      fullPath: '/marketing/forms/$formId'
      preLoaderRoute: typeof MarketingFormsFormIdRouteImport
      parentRoute: typeof MarketingFormsRoute
    }
    '/marketing/contacts/import': {
      id: '/marketing/contacts/import'
      path: '/import'
      fullPath: '/marketing/contacts/import'
      preLoaderRoute: typeof MarketingContactsImportRouteImport
      parentRoute: typeof MarketingContactsRoute
    }
    '/marketing/companies/$id': {
      id: '/marketing/companies/$id'
      path: '/marketing/companies/$id'
      fullPath: '/marketing/companies/$id'
      preLoaderRoute: typeof MarketingCompaniesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/campaigns/$id': {
      id: '/marketing/campaigns/$id'
      path: '/marketing/campaigns/$id'
      fullPath: '/marketing/campaigns/$id'
      preLoaderRoute: typeof MarketingCampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/personas/new': {
      id: '/collection/personas/new'
      path: '/collection/personas/new'
      fullPath: '/collection/personas/new'
      preLoaderRoute: typeof CollectionPersonasNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/personas/$personaId': {
      id: '/collection/personas/$personaId'
      path: '/collection/personas/$personaId'
      fullPath: '/collection/personas/$personaId'
      preLoaderRoute: typeof CollectionPersonasPersonaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/bounce': {
      id: '/api/webhooks/bounce'
      path: '/api/webhooks/bounce'
      fullPath: '/api/webhooks/bounce'
      preLoaderRoute: typeof ApiWebhooksBounceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/usage/suppressions': {
      id: '/api/usage/suppressions'
      path: '/suppressions'
      fullPath: '/api/usage/suppressions'
      preLoaderRoute: typeof ApiUsageSuppressionsRouteImport
      parentRoute: typeof ApiUsageRoute
    }
    '/api/usage/domains': {
      id: '/api/usage/domains'
      path: '/domains'
      fullPath: '/api/usage/domains'
      preLoaderRoute: typeof ApiUsageDomainsRouteImport
      parentRoute: typeof ApiUsageRoute
    }
    '/api/usage/allowance': {
      id: '/api/usage/allowance'
      path: '/allowance'
      fullPath: '/api/usage/allowance'
      preLoaderRoute: typeof ApiUsageAllowanceRouteImport
      parentRoute: typeof ApiUsageRoute
    }
    '/api/uploads/$filename': {
      id: '/api/uploads/$filename'
      path: '/api/uploads/$filename'
      fullPath: '/api/uploads/$filename'
      preLoaderRoute: typeof ApiUploadsFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track/open': {
      id: '/api/track/open'
      path: '/api/track/open'
      fullPath: '/api/track/open'
      preLoaderRoute: typeof ApiTrackOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track/click': {
      id: '/api/track/click'
      path: '/api/track/click'
      fullPath: '/api/track/click'
      preLoaderRoute: typeof ApiTrackClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/survey/$surveyId': {
      id: '/api/survey/$surveyId'
      path: '/api/survey/$surveyId'
      fullPath: '/api/survey/$surveyId'
      preLoaderRoute: typeof ApiSurveySurveyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/form-submit/$formId': {
      id: '/api/form-submit/$formId'
      path: '/api/form-submit/$formId'
      fullPath: '/api/form-submit/$formId'
      preLoaderRoute: typeof ApiFormSubmitFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilot/stream': {
      id: '/api/copilot/stream'
      path: '/api/copilot/stream'
      fullPath: '/api/copilot/stream'
      preLoaderRoute: typeof ApiCopilotStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilot/permission': {
      id: '/api/copilot/permission'
      path: '/api/copilot/permission'
      fullPath: '/api/copilot/permission'
      preLoaderRoute: typeof ApiCopilotPermissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/surveys/$surveyId/': {
      id: '/marketing/surveys/$surveyId/'
      path: '/$surveyId'
      fullPath: '/marketing/surveys/$surveyId/'
      preLoaderRoute: typeof MarketingSurveysSurveyIdIndexRouteImport
      parentRoute: typeof MarketingSurveysRoute
    }
    '/marketing/templates/$templateId/edit': {
      id: '/marketing/templates/$templateId/edit'
      path: '/$templateId/edit'
      fullPath: '/marketing/templates/$templateId/edit'
      preLoaderRoute: typeof MarketingTemplatesTemplateIdEditRouteImport
      parentRoute: typeof MarketingTemplatesRoute
    }
    '/marketing/surveys/$surveyId/edit': {
      id: '/marketing/surveys/$surveyId/edit'
      path: '/$surveyId/edit'
      fullPath: '/marketing/surveys/$surveyId/edit'
      preLoaderRoute: typeof MarketingSurveysSurveyIdEditRouteImport
      parentRoute: typeof MarketingSurveysRoute
    }
    '/api/webhooks/email/$provider': {
      id: '/api/webhooks/email/$provider'
      path: '/api/webhooks/email/$provider'
      fullPath: '/api/webhooks/email/$provider'
      preLoaderRoute: typeof ApiWebhooksEmailProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/surveys/$surveyId/token': {
      id: '/api/surveys/$surveyId/token'
      path: '/api/surveys/$surveyId/token'
      fullPath: '/api/surveys/$surveyId/token'
      preLoaderRoute: typeof ApiSurveysSurveyIdTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiUsageRouteChildren {
  ApiUsageAllowanceRoute: typeof ApiUsageAllowanceRoute
  ApiUsageDomainsRoute: typeof ApiUsageDomainsRoute
  ApiUsageSuppressionsRoute: typeof ApiUsageSuppressionsRoute
}

const ApiUsageRouteChildren: ApiUsageRouteChildren = {
  ApiUsageAllowanceRoute: ApiUsageAllowanceRoute,
  ApiUsageDomainsRoute: ApiUsageDomainsRoute,
  ApiUsageSuppressionsRoute: ApiUsageSuppressionsRoute,
}

const ApiUsageRouteWithChildren = ApiUsageRoute._addFileChildren(
  ApiUsageRouteChildren,
)

interface MarketingContactsRouteChildren {
  MarketingContactsImportRoute: typeof MarketingContactsImportRoute
  MarketingContactsIndexRoute: typeof MarketingContactsIndexRoute
}

const MarketingContactsRouteChildren: MarketingContactsRouteChildren = {
  MarketingContactsImportRoute: MarketingContactsImportRoute,
  MarketingContactsIndexRoute: MarketingContactsIndexRoute,
}

const MarketingContactsRouteWithChildren =
  MarketingContactsRoute._addFileChildren(MarketingContactsRouteChildren)

interface MarketingFormsRouteChildren {
  MarketingFormsFormIdRoute: typeof MarketingFormsFormIdRoute
  MarketingFormsIndexRoute: typeof MarketingFormsIndexRoute
}

const MarketingFormsRouteChildren: MarketingFormsRouteChildren = {
  MarketingFormsFormIdRoute: MarketingFormsFormIdRoute,
  MarketingFormsIndexRoute: MarketingFormsIndexRoute,
}

const MarketingFormsRouteWithChildren = MarketingFormsRoute._addFileChildren(
  MarketingFormsRouteChildren,
)

interface MarketingSurveysRouteChildren {
  MarketingSurveysIndexRoute: typeof MarketingSurveysIndexRoute
  MarketingSurveysSurveyIdEditRoute: typeof MarketingSurveysSurveyIdEditRoute
  MarketingSurveysSurveyIdIndexRoute: typeof MarketingSurveysSurveyIdIndexRoute
}

const MarketingSurveysRouteChildren: MarketingSurveysRouteChildren = {
  MarketingSurveysIndexRoute: MarketingSurveysIndexRoute,
  MarketingSurveysSurveyIdEditRoute: MarketingSurveysSurveyIdEditRoute,
  MarketingSurveysSurveyIdIndexRoute: MarketingSurveysSurveyIdIndexRoute,
}

const MarketingSurveysRouteWithChildren =
  MarketingSurveysRoute._addFileChildren(MarketingSurveysRouteChildren)

interface MarketingTemplatesRouteChildren {
  MarketingTemplatesIndexRoute: typeof MarketingTemplatesIndexRoute
  MarketingTemplatesTemplateIdEditRoute: typeof MarketingTemplatesTemplateIdEditRoute
}

const MarketingTemplatesRouteChildren: MarketingTemplatesRouteChildren = {
  MarketingTemplatesIndexRoute: MarketingTemplatesIndexRoute,
  MarketingTemplatesTemplateIdEditRoute: MarketingTemplatesTemplateIdEditRoute,
}

const MarketingTemplatesRouteWithChildren =
  MarketingTemplatesRoute._addFileChildren(MarketingTemplatesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiOptOutRoute: ApiOptOutRoute,
  ApiSubscribeRoute: ApiSubscribeRoute,
  ApiUnsubscribeRoute: ApiUnsubscribeRoute,
  ApiUsageRoute: ApiUsageRouteWithChildren,
  AuthLinkRoute: AuthLinkRoute,
  MarketingContactsRoute: MarketingContactsRouteWithChildren,
  MarketingFormsRoute: MarketingFormsRouteWithChildren,
  MarketingSurveysRoute: MarketingSurveysRouteWithChildren,
  MarketingTemplatesRoute: MarketingTemplatesRouteWithChildren,
  SSurveyIdRoute: SSurveyIdRoute,
  SalesPipelineRoute: SalesPipelineRoute,
  SalesTasksRoute: SalesTasksRoute,
  CollectionIndexRoute: CollectionIndexRoute,
  ApiCopilotPermissionRoute: ApiCopilotPermissionRoute,
  ApiCopilotStreamRoute: ApiCopilotStreamRoute,
  ApiFormSubmitFormIdRoute: ApiFormSubmitFormIdRoute,
  ApiSurveySurveyIdRoute: ApiSurveySurveyIdRoute,
  ApiTrackClickRoute: ApiTrackClickRoute,
  ApiTrackOpenRoute: ApiTrackOpenRoute,
  ApiUploadsFilenameRoute: ApiUploadsFilenameRoute,
  ApiWebhooksBounceRoute: ApiWebhooksBounceRoute,
  CollectionPersonasPersonaIdRoute: CollectionPersonasPersonaIdRoute,
  CollectionPersonasNewRoute: CollectionPersonasNewRoute,
  MarketingCampaignsIdRoute: MarketingCampaignsIdRoute,
  MarketingCompaniesIdRoute: MarketingCompaniesIdRoute,
  MarketingListsListIdRoute: MarketingListsListIdRoute,
  SalesDealsIdRoute: SalesDealsIdRoute,
  ApiUploadsIndexRoute: ApiUploadsIndexRoute,
  CollectionPersonasIndexRoute: CollectionPersonasIndexRoute,
  CollectionProspectSearchIndexRoute: CollectionProspectSearchIndexRoute,
  MarketingAnalyticsIndexRoute: MarketingAnalyticsIndexRoute,
  MarketingCampaignsIndexRoute: MarketingCampaignsIndexRoute,
  MarketingCompaniesIndexRoute: MarketingCompaniesIndexRoute,
  MarketingListsIndexRoute: MarketingListsIndexRoute,
  SalesDealsIndexRoute: SalesDealsIndexRoute,
  ApiSurveysSurveyIdTokenRoute: ApiSurveysSurveyIdTokenRoute,
  ApiWebhooksEmailProviderRoute: ApiWebhooksEmailProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
